version: 0.2

phases:
  install:
    commands:
      - sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo && sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo && sudo yum install -y apache-maven && mvn --version
      - echo "Test"
      
  build:
    commands:
      - echo "Build.."
artifacts:
  files:
    - '**/*'
