name: Commit date to master
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        TF_VAR_db_password: Earthly
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
      - name: Terraform Apply
        id: apply
        run: terraform apply
        continue-on-error: true
